destination: _site
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   /:title/
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
exclude:
  - Makefile
date_format: "%d %b %Y"
