application: markhansenconz 
version: 1
runtime: go
api_version: go1
handlers:
- url: /
  static_files: _site/index.html
  upload: _site/index.html
- url: /(.*)/
  static_files: _site/\1/index.html
  upload: .*/index\.html
- url: /
  static_dir: _site
pagespeed:
  enabled_rewriters:
  - MinifyCss
  - InlineJs
  - InlineImages
  - CollapseWhitespace
  - RemoveComments
  - RemoveQuotes
  - LeftTrimUrls
